### Import Packages

In [1206]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

### Load CSV data

In [1207]:
df = pd.read_csv("Churn_Modelling.csv")

In [1208]:
df.head(5)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [1209]:
df.isna().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [1210]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  str
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  str
 4   Gender           10000 non-null  str
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), str(3)
memory usage: 1.2 MB

In [1211]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [1212]:
df.shape

(10000, 13)

In [1213]:
df.duplicated().sum()

np.int64(0)

In [1214]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='str')

### Drop Customer Id and Surname

In [1215]:
df.drop(columns=["CustomerId","Surname"],inplace=True)

In [1216]:
df.head(3)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

### Convert categorical into numerical values

In [1217]:

# from sklearn.preprocessing import LabelEncoder

# encoder = LabelEncoder()
# df['Gender'] = encoder.fit_transform(df['Gender'])
# df['Geography'] = encoder.fit_transform(df['Geography'])

df = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True,dtype=int)

In [1218]:
df.head(2)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0

### Create input feature x and target label y

In [1219]:
x = df.drop(columns='Exited')
y = df['Exited']

In [1220]:
joblib.dump(x.columns.tolist(), "model_columns.pkl")

['model_columns.pkl']

In [1221]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [1222]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

### Split data intro training and testing sets

In [1223]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [1224]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8000, 11), (2000, 11), (8000,), (2000,))

### Bring all values to one scale

In [1225]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scale = scaler.fit_transform(x_train)
x_test_scale = scaler.transform(x_test)

### Train model

In [1226]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42, n_estimators=100)
rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [1227]:
rf_pred = rf_model.predict(x_test)
# rf_prob = rf_model.predict_proba(x_test)[:, 1]

In [1228]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

Random Forest Accuracy: 0.8645
[[1541   52]
 [ 219  188]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1593
           1       0.78      0.46      0.58       407

    accuracy                           0.86      2000
   macro avg       0.83      0.71      0.75      2000
weighted avg       0.86      0.86      0.85      2000

In [1229]:
# y_prob = rf_model.predict_proba(x_test_scale)[:, 1]

# plot_df = x_test.copy()
# plot_df["Actual"] = y_test.values
# plot_df["Predicted_Probability"] = rf_prob

# age_prob = plot_df.groupby("Age")["Predicted_Probability"].mean().reset_index()

# plt.figure(figsize=(8, 5))
# plt.plot(age_prob["Age"], age_prob["Predicted_Probability"], marker="o")

# plt.xlabel("Age")
# plt.ylabel("Average Predicted Probability of Exited")
# plt.title("Average Predicted Churn Probability by Age")
# plt.show()

In [1230]:
# age_grid = np.linspace(x_test["Age"].min(), x_test["Age"].max(), 200)

# # Create one average customer
# base_customer = x_train.median(numeric_only=True)

# # Repeat this customer for all ages
# age_curve = pd.DataFrame([base_customer] * len(age_grid))

# # Change only Age
# age_curve["Age"] = age_grid

# # Keep same column order as training data
# age_curve = age_curve[x_train.columns]

# # Scale using the same scaler
# age_curve_scaled = scaler.transform(age_curve)

# # Predict probability
# age_curve_prob = rf_prob.predict_proba(age_curve_scaled)[:, 1]

# plt.figure(figsize=(8, 5))
# plt.plot(age_grid, age_curve_prob)

# plt.xlabel("Age")
# plt.ylabel("Predicted Probability of Exited")
# plt.title("Smooth Logistic Regression Curve by Age")
# plt.show()

In [1231]:
from sklearn.linear_model import LogisticRegression
lg_model = LogisticRegression(max_iter=1000)
lg_model.fit(x_train_scale,y_train)

LogisticRegression(max_iter=1000)

In [1232]:
lg_pred = lg_model.predict(x_test_scale)

In [1233]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

print("Logistic Regression Accuracy:", accuracy_score(y_test, lg_pred))
print(confusion_matrix(y_test, lg_pred))
print(classification_report(y_test, lg_pred))

Logistic Regression Accuracy: 0.808
[[1540   53]
 [ 331   76]]
              precision    recall  f1-score   support

           0       0.82      0.97      0.89      1593
           1       0.59      0.19      0.28       407

    accuracy                           0.81      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

In [ ]:
joblib.dump(rf_model, "rf_model.pkl")

joblib.dump(scaler, "scaler.pkl")
print("model saved successfully")

model saved successfully